# Generated by Django 4.0.1 on 2022-05-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_Address',
            fields=[
                ('Adr_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Adr_Name', models.CharField(max_length=150)),
                ('Adr_Ville', models.CharField(max_length=150)),
                ('Adr_Province', models.CharField(max_length=150)),
                ('Adr_Pays', models.CharField(max_length=150)),
                ('Adr_Default', models.BooleanField()),
                ('Adr_ShipTo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='T_Company',
            fields=[
                ('C_Id', models.AutoField(primary_key=True, serialize=False)),
                ('C_Name', models.CharField(max_length=150)),
                ('C_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='T_User',
            fields=[
                ('U_Id', models.AutoField(primary_key=True, serialize=False)),
                ('U_Name', models.CharField(max_length=150)),
                ('U_Email', models.EmailField(max_length=254)),
                ('U_Pwd', models.CharField(max_length=150)),
                ('U_Admin', models.BooleanField()),
                ('U_Client', models.BooleanField()),
                ('U_Supplier', models.BooleanField()),
                ('Adr_ShipTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.t_address')),
                ('C_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.t_company')),
            ],
        ),
        migrations.CreateModel(
            name='T_Request',
            fields=[
                ('Req_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Req_Result', models.IntegerField(default=0)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin_Request', to='Accounts.t_user')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Request', to='Accounts.t_user')),
            ],
        ),
        migrations.AddField(
            model_name='t_address',
            name='C_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.t_company'),
        ),
    ]
