# Generated by Django 4.0.1 on 2022-05-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_t_user_adr_shipto'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_user',
            name='U_Tel',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
