# Generated by Django 4.0.1 on 2022-05-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_t_user_u_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_user',
            old_name='U_Name',
            new_name='U_FirstName',
        ),
        migrations.AddField(
            model_name='t_user',
            name='U_LastName',
            field=models.CharField(default='dsi', max_length=150),
            preserve_default=False,
        ),
    ]
