# Generated by Django 4.0.1 on 2022-05-25 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rename_u_name_t_user_u_firstname_t_user_u_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_address',
            name='Adr_ShipTo',
        ),
        migrations.RemoveField(
            model_name='t_address',
            name='C_Id',
        ),
        migrations.RemoveField(
            model_name='t_user',
            name='Adr_ShipTo',
        ),
        migrations.RemoveField(
            model_name='t_user',
            name='C_Id',
        ),
        migrations.AddField(
            model_name='t_address',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.t_user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='T_Company',
        ),
    ]
