# Generated by Django 4.0.1 on 2022-05-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_t_request_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_request',
            name='Req_Type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='', max_length=120),
            preserve_default=False,
        ),
    ]
