# Generated by Django 4.0.1 on 2022-05-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_t_request_req_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_request',
            name='Req_Type',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('admin', 'Admin')], max_length=120),
        ),
    ]
