# Generated by Django 4.0.1 on 2022-05-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_t_request_req_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_request',
            name='Admin',
        ),
    ]
