# Generated by Django 4.0.1 on 2022-06-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_t_user_u_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user',
            name='U_Statut',
            field=models.CharField(choices=[('autre', 'autre'), ('professionnel', 'Professionnel'), ('personnel', 'Personnel')], max_length=120),
        ),
    ]
