# Generated by Django 4.0.1 on 2022-05-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orderligne',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.t_order'),
        ),
    ]
