# Generated by Django 4.0.1 on 2022-05-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_t_orderligne_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_order',
            name='User',
        ),
    ]
