# Generated by Django 4.0.1 on 2022-05-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_t_user_adr_shipto'),
        ('Order', '0003_remove_t_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_order',
            name='User',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='User_Order', to='Accounts.t_user'),
            preserve_default=False,
        ),
    ]
